name: $(BuildID)
trigger:
  branches:
    include:
      - master

jobs:
  - job: pester_tests
    displayName: Pester tests
    timeoutInMinutes: 5
    pool:
      vmImage: 'windows-latest'
    steps:
      - powershell: |
          $dirs=@('Results','Coverage')
          foreach($dir in $dirs){
            New-Item -ItemType Directory -Force -Path "$(System.DefaultWorkingDirectory)\$dir"
          }
        displayName: Prepare Tests Directories

      - task: PowerShell@2
        displayName: Run Pester tests with Coverage
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)\006_InvokePester.ps1'
          pwsh: true

      - task: PublishTestResults@2
        displayName: Publish Pester Tests Results
        inputs:
          testResultsFormat: 'NUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)/Results/*pesterTEST.xml'
          failTaskOnFailedTests: true

      - script: 'dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.5.8'
        displayName: 'Install Coverage ReportGenerator tool'

      - script: 'reportgenerator -reports:"$(System.DefaultWorkingDirectory)/Coverage/*pesterCoverageTEST.xml" -targetdir:"$(System.DefaultWorkingDirectory)/Results/" -reporttypes:HtmlInline_AzurePipelines'
        displayName: 'Create Coverage reports'

      - task: PublishCodeCoverageResults@1
        displayName: Publish Pester Code Coverage Report
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/Coverage/*pesterCoverageTEST.xml'
          reportDirectory: "$(System.DefaultWorkingDirectory)/Results/"
